# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='production_year',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
    ]
