# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_auto_20171227_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
