# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_auto_20180105_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='mrl_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mrl_2',
            field=models.BooleanField(),
        ),
    ]
