# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20180105_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mrl',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='mrl_1',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='mrl_2',
        ),
    ]
