# Generated by Django 2.0.1 on 2018-01-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_auto_20180105_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
